package cn.nukkit.item.enchantment;

import cn.nukkit.MockServer;
import cn.nukkit.block.BlockID;
import cn.nukkit.item.Item;
import cn.nukkit.level.Level;
import cn.nukkit.level.Position;
import cn.nukkit.network.protocol.PlayerEnchantOptionsPacket;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;
import org.mockito.Mockito;

import java.lang.reflect.Method;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;
import static org.mockito.ArgumentMatchers.anyInt;
import static org.mockito.Mockito.lenient;

class EnchantmentHelperTest {

    @BeforeAll
    static void init() {
        MockServer.init();
    }

    @Test
    @SuppressWarnings("unchecked")
    void enchantingTableCandidatesExcludeTreasureAndCurses() throws Exception {
        Method filterApplicable = EnchantmentHelper.class.getDeclaredMethod("filterApplicable", Item.class, int.class);
        filterApplicable.setAccessible(true);

        List<Enchantment> candidates = (List<Enchantment>) filterApplicable.invoke(
                null,
                Item.get(Item.DIAMOND_PICKAXE),
                30
        );

        assertFalse(candidates.isEmpty(), "test item should have normal enchantment candidates");
        assertFalse(candidates.stream().anyMatch(enchantment -> enchantment.isTreasure() || enchantment.isCurse()));
    }

    // 见 #805：附魔台书本必须能刷出附魔选项。
    // <p>
    // See #805: a book in the enchanting table must yield enchantment candidates.
    @Test
    @SuppressWarnings("unchecked")
    void enchantingTableAcceptsPlainBook() throws Exception {
        Method filterApplicable = EnchantmentHelper.class.getDeclaredMethod("filterApplicable", Item.class, int.class);
        filterApplicable.setAccessible(true);

        List<Enchantment> candidates = (List<Enchantment>) filterApplicable.invoke(
                null,
                Item.get(Item.BOOK),
                30
        );

        assertFalse(candidates.isEmpty(), "book should have enchantment candidates in the enchanting table");
        assertFalse(candidates.stream().anyMatch(enchantment -> enchantment.isTreasure() || enchantment.isCurse()));

        // 附魔台生成的三档选项不应为空（无书架环境下调用）。
        // <p>
        // The three enchantment options generated by the table must not be empty (no bookshelves).
        List<?> options = EnchantmentHelper.generateOptions(positionWithoutBookshelves(), Item.get(Item.BOOK), 42L);
        assertFalse(options.isEmpty(), "enchanting table should publish options for a book");
        assertTrue(candidates.stream().anyMatch(e -> e.canEnchant(Item.get(Item.BOOK))),
                "every candidate must be applicable to a plain book");
    }

    // 见 #808：无论书架数量多少，附魔台所有选项所需经验等级均不应超过 30。
    // <p>
    // See #808: required xp level of every enchanting table option must stay <= 30
    // regardless of bookshelf count.
    @Test
    void enchantingTableRequiredLevelNeverExceeds30() {
        // 构造一个原版最大书架环境：附魔台置于 (0,64,0)，仅在距 2 格的合法书架位置
        // （且中间为空气）放置 BOOKSHELF，其余方块为 AIR。这样 countBookshelves 会达到上限 15。
        // <p>Build a vanilla max-bookshelf layout: table at (0,64,0), BOOKSHELF only on valid
        // 2-block-distant columns with clear air between; everything else AIR. This drives
        // countBookshelves to the 15 cap.
        Level level = Mockito.mock(Level.class);
        Mockito.when(level.getBlockIdAt(anyInt(), anyInt(), anyInt())).thenAnswer(inv -> {
            int x = inv.getArgument(0);
            int y = inv.getArgument(1);
            int z = inv.getArgument(2);
            // 仅 y=64/65（附魔台同高及上方一层）且 X/Z 距离恰为 2 视为书架
            // <p>Only y=64/65 columns exactly 2 blocks away on X or Z are bookshelves.
            boolean twoAway = Math.abs(x) == 2 || Math.abs(z) == 2;
            boolean inLayer = y == 64 || y == 65;
            return (twoAway && inLayer) ? BlockID.BOOKSHELF : BlockID.AIR;
        });
        Position tablePos = new Position(0, 64, 0, level);

        // 多个 seed 验证边界
        // <p>Validate across several seeds.
        for (long seed = 0L; seed < 50L; seed++) {
            List<PlayerEnchantOptionsPacket.EnchantOptionData> options =
                    EnchantmentHelper.generateOptions(tablePos, Item.get(Item.DIAMOND_SWORD), seed);
            assertFalse(options.isEmpty(), "options should be generated at full bookshelves");
            for (PlayerEnchantOptionsPacket.EnchantOptionData option : options) {
                assertTrue(option.getMinLevel() <= 30,
                        "required level must not exceed 30 (seed=" + seed + ", got " + option.getMinLevel() + ")");
                assertTrue(option.getMinLevel() >= 1,
                        "required level must be >= 1 (seed=" + seed + ", got " + option.getMinLevel() + ")");
            }
        }
    }

    private static Position positionWithoutBookshelves() {
        Level level = Mockito.mock(Level.class);
        lenient().when(level.getBlockIdAt(anyInt(), anyInt(), anyInt())).thenReturn(BlockID.AIR);
        return new Position(0, 64, 0, level);
    }
}
