package cn.nukkit.item.enchantment;

import cn.nukkit.MockServer;
import cn.nukkit.item.Item;
import org.junit.jupiter.api.BeforeAll;
import org.junit.jupiter.api.Test;

import java.lang.reflect.Method;
import java.util.List;

import static org.junit.jupiter.api.Assertions.assertFalse;
import static org.junit.jupiter.api.Assertions.assertTrue;

class EnchantmentHelperTest {

    @BeforeAll
    static void init() {
        MockServer.init();
    }

    @Test
    @SuppressWarnings("unchecked")
    void enchantingTableCandidatesExcludeTreasureAndCurses() throws Exception {
        Method filterApplicable = EnchantmentHelper.class.getDeclaredMethod("filterApplicable", Item.class, int.class);
        filterApplicable.setAccessible(true);

        List<Enchantment> candidates = (List<Enchantment>) filterApplicable.invoke(
                null,
                Item.get(Item.DIAMOND_PICKAXE),
                30
        );

        assertFalse(candidates.isEmpty(), "test item should have normal enchantment candidates");
        assertFalse(candidates.stream().anyMatch(enchantment -> enchantment.isTreasure() || enchantment.isCurse()));
    }

    // 见 #805：附魔台书本必须能刷出附魔选项。
    // <p>
    // See #805: a book in the enchanting table must yield enchantment candidates.
    @Test
    @SuppressWarnings("unchecked")
    void enchantingTableAcceptsPlainBook() throws Exception {
        Method filterApplicable = EnchantmentHelper.class.getDeclaredMethod("filterApplicable", Item.class, int.class);
        filterApplicable.setAccessible(true);

        List<Enchantment> candidates = (List<Enchantment>) filterApplicable.invoke(
                null,
                Item.get(Item.BOOK),
                30
        );

        assertFalse(candidates.isEmpty(), "book should have enchantment candidates in the enchanting table");
        assertFalse(candidates.stream().anyMatch(enchantment -> enchantment.isTreasure() || enchantment.isCurse()));

        // 附魔台生成的三档选项不应为空。
        // <p>
        // The three enchantment options generated by the table must not be empty.
        List<?> options = EnchantmentHelper.generateOptions(Item.get(Item.BOOK), 42L);
        assertFalse(options.isEmpty(), "enchanting table should publish options for a book");
        assertTrue(candidates.stream().anyMatch(e -> e.canEnchant(Item.get(Item.BOOK))),
                "every candidate must be applicable to a plain book");
    }
}
