package cn.nukkit.network.protocol;

import it.unimi.dsi.fastutil.objects.ObjectArrayList;
import lombok.ToString;

import java.util.List;

/**
 * Created by CreeperFace on 5.3.2017.
 */
@ToString
public class MapInfoRequestPacket extends DataPacket {

    public static final byte NETWORK_ID = ProtocolInfo.MAP_INFO_REQUEST_PACKET;

    public long mapId;

    /**
     * Sends pixels that are generated by the client to the server.
     *
     * @since 1.19.20
     */
    public final List<MapPixel> pixels = new ObjectArrayList<>();

    @Override
    public byte pid() {
        return NETWORK_ID;
    }

    @Override
    public void decode() {
        mapId = this.getVarLong();

        if (this.protocol >= ProtocolInfo.v1_19_20) {
            // since v544: uint32 length + N x (uint32 pixel + uint16 index), all little-endian, no compression
            int count = this.getLInt();
            for (int i = 0; i < count; i++) {
                MapPixel pixel = new MapPixel();
                pixel.pixel = this.getLInt();
                pixel.index = this.getLShort();
                this.pixels.add(pixel);
            }
        }
    }

    @Override
    public void encode() {
        this.encodeUnsupported();
    }

    public static class MapPixel {
        /**
         * Colour value of pixel
         */
        public int pixel;
        /**
         * Pixel index in map.
         */
        public int index;
    }
}
