name: Java CI with Gradle

on:
  push:
    branches: [ feature/java-25 ]
  pull_request:
    branches: [ feature/java-25 ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      - name: Set up JDK 25
        uses: actions/setup-java@v4
        with:
          java-version: 25
          distribution: 'temurin'
          cache: gradle

      - name: Build with Gradle
        run: |
          ./gradlew shadowJar --no-daemon --quiet \
            -Dorg.gradle.jvmargs="--enable-native-access=ALL-UNNAMED" \
            -Dorg.gradle.internal.launcher.welcomeMessageEnabled=false

      - uses: actions/upload-artifact@v4
        with:
          name: Nukkit-MOT
          path: target/*.jar
          if-no-files-found: error
          retention-days: 30

      - name: Prepare and send data to MineBBS
        if: success() && github.event_name == 'push' && github.repository == 'MemoriesOfTime/Nukkit-MOT' && (github.ref == 'refs/heads/master' || github.ref == 'refs/heads/feature/java-25')
        run: |
          SHA_SHORT=$(git rev-parse --short HEAD)
          COMMIT_MSG=$(echo '${{ github.event.commits[0].message }}' | head -n 1)
          CURRENT_TIME=$(date -u +"%Y/%m/%d-%H:%M:%S" -d "+8 hours")
          
          curl -X POST 'https://api.minebbs.com/api/openapi/v1/resources/5934/update' \
            -H 'Authorization: Bearer ${{ secrets.MINEBBS_API_KEY }}' \
            -H 'Content-Type: application/json' \
            -d "{
              \"title\": \"${{ github.ref_name }}-${SHA_SHORT}\",
              \"description\": \"${COMMIT_MSG}\",
              \"new_version\": \"${CURRENT_TIME}\",
              \"file_url\": \"https://motci.cn/job/Nukkit-MOT/\"
            }" \
            -f -s || true  # -s = silent, -f = fail silently, || true